# Generated by Django 5.1.1 on 2024-11-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_first_name_user_last_name_user_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
    ]
