# Generated by Django 5.1.3 on 2024-11-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sec_id',
            field=models.CharField(default=''),
        ),
    ]
