# Generated by Django 5.1.1 on 2025-03-05 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='longest_exchange',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='shortest_exchange',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.CharField(default='Undefined'),
        ),
        migrations.AddField(
            model_name='user',
            name='tourney_win_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Tourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField()),
                ('name2', models.CharField()),
                ('name3', models.CharField()),
                ('name4', models.CharField()),
                ('name5', models.CharField()),
                ('name6', models.CharField()),
                ('name7', models.CharField()),
                ('name8', models.CharField()),
                ('winner_match1', models.CharField()),
                ('winner_match2', models.CharField()),
                ('winner_match3', models.CharField()),
                ('winner_match4', models.CharField()),
                ('winner_match5', models.CharField()),
                ('winner_match6', models.CharField()),
                ('winner_match7', models.CharField()),
                ('tourney_id', models.CharField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
